"""
Psiquis-X: GitHub Integration Skill
Provides the autonomous framework with the ability to publish generated artifacts
(Markdown reports, code snippets, Mermaid diagrams) directly to GitHub Gists.

Requirements:
- A valid GitHub Personal Access Token (PAT) with 'gist' scope.
"""

import os
import json
import requests
from typing import Dict, Optional
import logging

logger = logging.getLogger(__name__)

def create_github_gist(
    description: str,
    files: Dict[str, Dict[str, str]],
    is_public: bool = True,
    github_token: Optional[str] = None
) -> str:
    """
    Creates a new GitHub Gist autonomously.
    
    Args:
        description (str): A description for the Gist.
        files (dict): A dictionary where keys are filenames and values are dicts 
                      containing the 'content' key. 
                      Example: {"report.md": {"content": "# Hello World"}}
        is_public (bool): Whether the Gist should be public. Defaults to True.
        github_token (str, optional): The GitHub PAT. If None, it attempts to load from 
                                      the GITHUB_PAT environment variable.
                                      
    Returns:
        str: The URL of the created Gist, or an error message if failed.
    """
    # Force use of the new token to avoid stale environment variables in PowerShell
    token = github_token or os.environ.get("GITHUB_PAT")
    
    if not token:
        error_msg = "GitHub Token missing. Provide it as an argument or set GITHUB_PAT env var."
        logger.error(error_msg)
        return f"Error: {error_msg}"

    url = "https://api.github.com/gists"
    
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json",
    }
    
    payload = {
        "description": description,
        "public": is_public,
        "files": files
    }
    
    try:
        response = requests.post(url, headers=headers, data=json.dumps(payload))
        response.raise_for_status() # Raise an exception for HTTP errors
        
        # Parse the JSON response
        gist_data = response.json()
        gist_url = gist_data.get("html_url")
        
        logger.info(f"Successfully created Gist: {gist_url}")
        return gist_url
        
    except requests.exceptions.RequestException as e:
        logger.error(f"Failed to create Gist. Error: {e}")
        # Return the specific error from GitHub if available
        if hasattr(e, 'response') and e.response is not None:
             logger.error(f"GitHub API Response: {e.response.text}")
             return f"Error HTTP {e.response.status_code}: {e.response.text}"
        return f"Error connecting to GitHub API: {str(e)}"

# --- Simple Test Execution Guard ---
if __name__ == "__main__":
    # If run directly, run a quick sanity test (requires GITHUB_PAT env var)
    print("Testing GitHub Integration Skill...")
    test_files = {
        "psiquis_x_test.md": {
            "content": "# Psiquis-X Autonomous Test\n\nThis is a test Gist generated by the Cortex router."
        }
    }
    
    result_url = create_github_gist(
        description="Psiquis-X Autonomous Systems Test",
        files=test_files,
        is_public=False # Keep it hidden during tests
    )
    
    print(f"Result: {result_url}")
